---
- hosts: master
  become: yes
  tasks:
    - name: Generate SSH key pair
      openssh_keypair:
        path: ~/.ssh/id_rsa
        size: 2048

- hosts: slave
  become: yes
  tasks:
    - name: Ensure ~/.ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Copy SSH public key from master to slave
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        path: ~/.ssh/authorized_keys
        exclusive: true
